#include <qstring.h>
#include <thread>
#include <vector>
#include <random>
#include <qwidget.h>
#include <qtimer.h>
#include <qpainter.h>
#include <qmainwindow.h>
#include <qfile.h>
#include <qdir.h>
#include <qdialog.h>
#include <qfiledialog.h>
#include <qfileinfo.h>
#include <functional>
#include <chrono>
#include <atomic>